### PR TITLE
plotting submodule for julia/Stheno.jl

### LINKED ISSUE #25: Plotting Recipes
It's useful to be able to produce nice pretty plots of GPs in 1 dimension. Currently, this is a bit of a pain because no plotting recipes have been implemented. If we implemented some, it would significantly simplify a _lot_ of the plotting that we do.

(If you're interested in making this happen, I'm happy to discuss)

### PR DESCRIPTION
**Pull request by ritesh99rakesh**
**[WIP]**
Fixes #25

### CODE REVIEW

**Comment by ritesh99rakesh** [comment]
@willtebbutt, when I am running your code on Jupyter Notebook: https://github.com/willtebbutt/Stheno.jl/blob/901ecddb0c1571ef7dc1c5dd19af9f283170c761/examples/toy/vanilla_noisy_regression.jl#L69
I get the following error: `only png or svg allowed. got: :html`
How can I get correct this error?

**Comment by willtebbutt** [comment]
Thanks for opening the PR.

Could you provide the full stack trace for your error?

**Comment by ritesh99rakesh** [comment]
I tried running this: https://github.com/willtebbutt/Stheno.jl/blob/901ecddb0c1571ef7dc1c5dd19af9f283170c761/examples/toy/non_iid_noise.jl,
 and there is no error. But for above code I got this error:
```
only png or svg allowed. got: :html

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] _show(::Base.GenericIOBuffer{Array{UInt8,1}}, ::MIME{Symbol("text/html")}, ::Plots.Plot{Plots.PlotlyBackend}) at /home/riteshk/.julia/packages/Plots/QYETN/src/output.jl:176
 [3] show(::Base.GenericIOBuffer{Array{UInt8,1}}, ::MIME{Symbol("text/html")}, ::Plots.Plot{Plots.PlotlyBackend}) at /home/riteshk/.julia/packages/Plots/QYETN/src/output.jl:198
 [4] #sprint#340(::Nothing, ::Int64, ::Function, ::Function, ::MIME{Symbol("text/html")}, ::Vararg{Any,N} where N) at ./strings/io.jl:101
 [5] sprint(::Function, ::MIME{Symbol("text/html")}, ::Vararg{Any,N} where N) at ./strings/io.jl:97
 [6] _ijulia_display_dict(::Plots.Plot{Plots.PlotlyBackend}) at /home/riteshk/.julia/packages/Plots/QYETN/src/ijulia.jl:53
 [7] display_dict at /home/riteshk/.julia/packages/Plots/QYETN/src/init.jl:42 [inlined]
 [8] display(::IJulia.InlineDisplay, ::Plots.Plot{Plots.PlotlyBackend}) at /home/riteshk/.julia/packages/IJulia/4UizY/src/inline.jl:89
 [9] display(::Any) at ./multimedia.jl:287
 [10] top-level scope at In[2]:45```

**Comment by willtebbutt** [comment]
Hmm okay. Are you running from the repl or from a notebook? I can see a refernce to `IJulia` on the third line of your stack trace. Possibly plotly doesn't play nicely with IJulia? Perhaps try running the whole script without line 67?

**Comment by willtebbutt** [comment]
@ritesh99rakesh what's the state of this PR? Are you planning to continue working on it?

**Comment by ritesh99rakesh** [comment]
Hi @willtebbutt! I currently have my end semester exams and so could not give much time towards this PR. My exam will end on 29 Apr morning, and the first thing I will do is to complete this PR. You can expect it to complete it by 30 Apr latest. Sorry for the delay but I will finish it ASAP.

**Comment by willtebbutt** [comment]
No problem at all, just wanted to know what's going on with it. No hurry!

**Comment by willtebbutt** [comment]
Closing this branch for now. Please re-open if progress is made.

**Pull request closed without merging**
