### PR TITLE
Getting Started Documentation

### PR DESCRIPTION
**Pull request by willtebbutt**

### CODE REVIEW

**Comment by willtebbutt** [comment]
Might well try this again with the images stored elsewhere so as to avoid bloating the repo

**Comment by cpfiffer** [comment]
Looks nice and helpful to me.

**Comment by mohamed82008** [comment]
Looks good. I would have liked it more if there was a little bit of math explaining what's a GP and the math that Stheno makes easier.

**Comment by willtebbutt** [comment]
> Looks good. I would have liked it more if there was a little bit of math explaining what's a GP and the math that Stheno makes easier.

Regarding what a GP is, I suspect I'm best off linking to external resources on the subject as they're notoriously difficult to explain clearly. Would that be sufficient @mohamed82008 ?

I'll be adding a thing on what Stheno makes easier soon -- will add it in a TODO section for now though :)

**Comment by mohamed82008** [comment]
Sounds good. One day I would love to read this repo's src in detail and learn about GPs properly from a book. It would be nice to have mathy references in the docs to relate to the content in GP learning material.

**Pull request merged**
